### ISSUE TITLE
Recursive search with -x option

### ISSUE THREAD

**Issue by Crypto-Cat** [epi052/recursive-gobuster#2]
Hi,

When you run the program using the -x flag to pass in file extensions, it will recursively look for directories as if it were a directory e.g. If it finds:

www.example.com/test/index.php

it will start to search:

www.example.com/test/index.php/admin.php
www.example.com/test/index.php/login/
www.example.com/test/index.php/test.js

etc....

Is it possible to change it so that recursive search is only applied to directories?

Thanks,
Crypto

**Comment by epi052** [comment]
Yea, that's definitely fixable.  I'll have something ready in the next day or two.  Thanks for letting me know!

**Comment by epi052** [comment]
Fixed.
