### ISSUE TITLE
Threads option seems to be broken

### ISSUE THREAD

**Issue by JustOneMoreDog** [epi052/recursive-gobuster#4]
```
root@kalix64:~/htb# recursive-gobuster.pyz -t 30 -w /usr/share/seclists/Discovery/Web-Content/common.txt -x aspx,html,php,asp http://10.10.10.43/
Error: unknown command "30" for "gobuster"
Run 'gobuster --help' for usage.
```
It then hangs here until I ctrl c it.  

It does it for the default usage as well 
```
root@kalix64:~/htb# recursive-gobuster.pyz http://10.10.10.43/
Error: unknown command "20" for "gobuster"
Run 'gobuster --help' for usage.
```

**Comment by niah2209** [comment]
looks like it doesn't work well with the new implementation of the new gobuster, as it needs "dir" 
 or "dns" to specify which mode you want. This project needs an update to reflect that

**Comment by epi052** [comment]
Thanks for pointing that out!  I'll get it updated today.

**Comment by epi052** [comment]
also, i apologize for the late response, for whatever reason my watch settings didn't include this repository.  not sure why.  should receive notifications on issues now

**Comment by epi052** [comment]
appreciate the heads up.  fixed now.  should work with either version of `gobuster`.

**Comment by JustOneMoreDog** [comment]
sorry I never saw your response until now but I came back to see if this was up and running as I needed it again.  Thanks for fixing this!

**Comment by epi052** [comment]
no sweat, glad you're getting some use out of it!
